### ISSUE TITLE
Make master the stable branch

### ISSUE THREAD

**Issue by ryanstull** [matthax/EyeContext#3]
Make master the stable branch so people visiting the repo will see the stable branch automatically

**Comment by matthax** [comment]
I am not entirely sure how to do that, what do I need to do?                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the Verizon Wireless 4G LTE network.                                                                                                                                                                                                                From: Ryan StullSent: Monday, April 20, 2015 7:19 PMTo: matthax/EvoHaxReply To: matthax/EvoHaxSubject: [EvoHax] Make master the stable branch (#3)Make master the stable branch so people visiting the repo will see the stable branch automatically

—Reply to this email directly or view it on GitHub.

**Comment by ryanstull** [comment]
I can take care of it

**Comment by matthax** [comment]
Okay I'll rename the repository                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the Verizon Wireless 4G LTE network.                                                                                                                                                                                                                From: Ryan StullSent: Monday, April 20, 2015 9:16 PMTo: matthax/EvoHaxReply To: matthax/EvoHaxCc: matthaxSubject: Re: [EvoHax] Make master the stable branch (#3)I can take care of it

—Reply to this email directly or view it on GitHub.

**Comment by matthax** [comment]
Alright actually I think I got it all working, stable and master are the same as of right now, mark sucks is gone and I'll replace testing with the current stable too, we can work from that branch to keep things nice between updates                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the Verizon Wireless 4G LTE network.                                                                                                                                                                                                                From: Ryan StullSent: Monday, April 20, 2015 9:16 PMTo: matthax/EvoHaxReply To: matthax/EvoHaxCc: matthaxSubject: Re: [EvoHax] Make master the stable branch (#3)I can take care of it

—Reply to this email directly or view it on GitHub.

**Comment by ryanstull** [comment]
Nice! If you could rename the repo that'd be awesome, then I'll close the issue

**Comment by matthax** [comment]
Should be renamed                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the Verizon Wireless 4G LTE network.                                                                                                                                                                                                                From: Ryan StullSent: Monday, April 20, 2015 9:44 PMTo: matthax/EvoHaxReply To: matthax/EvoHaxCc: matthaxSubject: Re: [EvoHax] Make master the stable branch (#3)Nice! If you could rename the repo that'd be awesome, then I'll close the issue

—Reply to this email directly or view it on GitHub.

**Comment by ryanstull** [comment]
Nice

**Comment by matthax** [comment]
Alright so did you change anything in the test branch we should keep? And I've got a few ideas to improve performance. The first, of course, being async if possible. The second would be chunking the text we input at like a buffer of 500 chars, we'll need to find an optimal quantity, then updating the chunks one by one. This way the icons will be added by section from top to bottom and not all at once after working for a while.It'll be cool to see how much we can do                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the Verizon Wireless 4G LTE network.                                                                                                                                                                                                                From: Ryan StullSent: Monday, April 20, 2015 9:49 PMTo: matthax/EyeContextReply To: matthax/EyeContextCc: matthaxSubject: Re: [EyeContext] Make master the stable branch (#3)Nice

—Reply to this email directly or view it on GitHub.

**Comment by mjblack001** [comment]
No Mark sux branch? What a shame.

**Comment by ryanstull** [comment]
No test doesn't really have anything important in it.  Everything thing in
it is in master.  Also I like the ideas for improving performance.

Also have we basically used all the icons we have our are there more we
have yet to assign?

**Comment by matthax** [comment]
Sorry ‎I guess SOMEONE WANTS TO TAKE SOMETHING SERIOUSLY. I mean come on, being serious is for winners but shh, don't tell HIM I said this                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the Verizon Wireless 4G LTE network.                                                                                                                                                                                                                From: mjblack001Sent: Monday, April 20, 2015 9:58 PMTo: matthax/EyeContextReply To: matthax/EyeContextCc: matthaxSubject: Re: [EyeContext] Make master the stable branch (#3)No Mark sux branch? What a shame.
On Apr 20, 2015 9:54 PM, "matthax" <notifications@github.com> wrote:

> Alright so did you change anything in the test branch we should keep? And
> I've got a few ideas to improve performance. The first, of course, being
> async if possible. The second would be chunking the text we input at like a
> buffer of 500 chars, we'll need to find an optimal quantity, then updating
> the chunks one by one. This way the icons will be added by section from top
> to bottom and not all at once after working for a while.It'll be cool to
> see how much we can do
> Sent from my BlackBerry 10 smartphone on the Verizon Wireless 4G LTE network.
> From: Ryan StullSent: Monday, April 20, 2015 9:49 PMTo:
> matthax/EyeContextReply To: matthax/EyeContextCc: matthaxSubject: Re:
> [EyeContext] Make master the stable branch (#3)Nice
>
> —Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/matthax/EyeContext/issues/3#issuecomment-94610447>.
>


—Reply to this email directly or view it on GitHub.

**Comment by matthax** [comment]
There are probably a solid 200-300 that are defiantly usable that we still need to assign                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the Verizon Wireless 4G LTE network.                                                                                                                                                                                                                From: Ryan StullSent: Monday, April 20, 2015 9:59 PMTo: matthax/EyeContextReply To: matthax/EyeContextCc: matthaxSubject: Re: [EyeContext] Make master the stable branch (#3)No test doesn't really have anything important in it.  Everything thing in
it is in master.  Also I like the ideas for improving performance.

Also have we basically used all the icons we have our are there more we
have yet to assign?
On Apr 20, 2015 9:54 PM, "matthax" <notifications@github.com> wrote:

> Alright so did you change anything in the test branch we should keep? And
> I've got a few ideas to improve performance. The first, of course, being
> async if possible. The second would be chunking the text we input at like a
> buffer of 500 chars, we'll need to find an optimal quantity, then updating
> the chunks one by one. This way the icons will be added by section from top
> to bottom and not all at once after working for a while.It'll be cool to
> see how much we can do
> Sent from my BlackBerry 10 smartphone on the Verizon Wireless 4G LTE network.
> From: Ryan StullSent: Monday, April 20, 2015 9:49 PMTo:
> matthax/EyeContextReply To: matthax/EyeContextCc: matthaxSubject: Re:
> [EyeContext] Make master the stable branch (#3)Nice
>
> —Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/matthax/EyeContext/issues/3#issuecomment-94610447>.
>


—Reply to this email directly or view it on GitHub.
